import type { Project } from '../types';

export const projectsEn: Project[] = [
  {
    id: 'portfolio-website',
    title: 'Portfolio Website',
    description: 'High-performance developer portfolio optimized for SEO.',
    tech: ['Next.js', 'Framer Motion'],
    category: 'frontend',
    github: 'https://github.com/Primar1Ui/refined-man-page',
    live: 'https://v0-personal-portfolio-website-mocha-eta.vercel.app/',
    role: 'Designer & developer',
    results: 'Designed and developed a fast, SEO-friendly personal brand site with a strong contact funnel.',
    image: '/images/projects/portfolio-website.png',
  },
  {
    id: 'baxauto-website',
    title: 'BaxAuto Website',
    description: 'Marketing website for BaxAuto, focused on clear service presentation and clean UI.',
    tech: ['Next.js', 'Tailwind CSS'],
    category: 'frontend',
    github: 'https://github.com/Primar1Ui/v0-baxauto-website-development',
    live: 'https://v0-baxauto-website-development-qyak.vercel.app/',
    role: 'Frontend developer',
    results: 'Delivered a responsive landing experience tailored to the client brand.',
    image: '/images/projects/baxauto-website.png',
  },
  {
    id: 'smart-spend-dashboard',
    title: 'Smart Expense & Budget Dashboard',
    description: 'Web app for tracking expenses and managing budgets with an intuitive dashboard.',
    tech: ['React', 'Next.js', 'Tailwind CSS'],
    category: 'full-stack',
    github: 'https://github.com/Primar1Ui/smart-spend-dashboard',
    live: 'https://smart-spend-dashboard.vercel.app/',
    role: 'Full-stack developer',
    results: 'Built a smart spend dashboard for expense tracking and budget visibility.',
    image: '/images/projects/smart-spend-dashboard.png',
    featured: true,
    metrics: ['Expense tracking', 'Budget dashboard', 'Production deploy'],
  },
  {
    id: 'refined-man',
    title: 'Refined Man',
    description: "Premium men's accessories e-commerce site with clean UI and smooth experience.",
    tech: ['Next.js', 'Tailwind CSS'],
    category: 'frontend',
    live: 'https://refined-man.vercel.app/',
    role: 'Frontend developer',
    results: "Designed and built a polished men's accessories storefront.",
    image: '/images/projects/refined-man.png',
  },
];
