import type { Project } from '../types';

export const projectsEs: Project[] = [
  {
    id: 'portfolio-website',
    title: 'Sitio portfolio',
    description: 'Portfolio de desarrollador de alto rendimiento optimizado para SEO.',
    tech: ['Next.js', 'Framer Motion'],
    category: 'frontend',
    github: 'https://github.com/Primar1Ui/refined-man-page',
    live: 'https://v0-personal-portfolio-website-mocha-eta.vercel.app/',
    role: 'Diseñador y desarrollador',
    results: 'Diseñé y desarrollé un sitio personal rápido, orientado a SEO, con un embudo de contacto claro.',
    image: '/images/projects/portfolio-website.png',
  },
  {
    id: 'baxauto-website',
    title: 'Sitio web BaxAuto',
    description: 'Sitio de marketing para BaxAuto, con servicios claros y una UI limpia.',
    tech: ['Next.js', 'Tailwind CSS'],
    category: 'frontend',
    github: 'https://github.com/Primar1Ui/v0-baxauto-website-development',
    live: 'https://v0-baxauto-website-development-qyak.vercel.app/',
    role: 'Desarrollador frontend',
    results: 'Entregué una landing responsive adaptada a la marca del cliente.',
    image: '/images/projects/baxauto-website.png',
  },
  {
    id: 'smart-spend-dashboard',
    title: 'Panel de gastos y presupuesto',
    description: 'App web para registrar gastos y gestionar presupuestos con un panel intuitivo.',
    tech: ['React', 'Next.js', 'Tailwind CSS'],
    category: 'full-stack',
    github: 'https://github.com/Primar1Ui/smart-spend-dashboard',
    live: 'https://smart-spend-dashboard.vercel.app/',
    role: 'Desarrollador full stack',
    results: 'Construí un panel de gastos inteligente para seguimiento de presupuesto.',
    image: '/images/projects/smart-spend-dashboard.png',
    featured: true,
    metrics: ['Seguimiento de gastos', 'Panel de presupuesto', 'Despliegue en producción'],
  },
  {
    id: 'refined-man',
    title: 'Refined Man',
    description: 'Tienda e-commerce de accesorios masculinos premium con UI limpia y buena experiencia.',
    tech: ['Next.js', 'Tailwind CSS'],
    category: 'frontend',
    live: 'https://refined-man.vercel.app/',
    role: 'Desarrollador frontend',
    results: 'Diseñé y construí una tienda pulida de accesorios masculinos.',
    image: '/images/projects/refined-man.png',
  },
];
