import type { Project } from '../types';

export const projectsFr: Project[] = [
  {
    id: 'portfolio-website',
    title: 'Site portfolio',
    description: 'Portfolio développeur performant, optimisé pour le SEO.',
    tech: ['Next.js', 'Framer Motion'],
    category: 'frontend',
    github: 'https://github.com/Primar1Ui/refined-man-page',
    live: 'https://v0-personal-portfolio-website-mocha-eta.vercel.app/',
    role: 'Designer et développeur',
    results: 'Conçu et développé un site personnel rapide, SEO-friendly, avec un funnel contact clair.',
    image: '/images/projects/portfolio-website.png',
  },
  {
    id: 'baxauto-website',
    title: 'Site web BaxAuto',
    description: 'Site marketing pour BaxAuto, centré sur des services clairs et une UI propre.',
    tech: ['Next.js', 'Tailwind CSS'],
    category: 'frontend',
    github: 'https://github.com/Primar1Ui/v0-baxauto-website-development',
    live: 'https://v0-baxauto-website-development-qyak.vercel.app/',
    role: 'Développeur frontend',
    results: 'Livré une landing responsive alignée sur la marque du client.',
    image: '/images/projects/baxauto-website.png',
  },
  {
    id: 'smart-spend-dashboard',
    title: 'Tableau de bord dépenses et budget',
    description: 'App web pour suivre les dépenses et gérer les budgets avec un tableau de bord intuitif.',
    tech: ['React', 'Next.js', 'Tailwind CSS'],
    category: 'full-stack',
    github: 'https://github.com/Primar1Ui/smart-spend-dashboard',
    live: 'https://smart-spend-dashboard.vercel.app/',
    role: 'Développeur full stack',
    results: 'Construit un tableau de bord de dépenses pour le suivi budgétaire.',
    image: '/images/projects/smart-spend-dashboard.png',
    featured: true,
    metrics: ['Suivi des dépenses', 'Tableau de budget', 'Déploiement production'],
  },
  {
    id: 'refined-man',
    title: 'Refined Man',
    description: 'Boutique e-commerce d accessoires masculins premium, UI propre et expérience fluide.',
    tech: ['Next.js', 'Tailwind CSS'],
    category: 'frontend',
    live: 'https://refined-man.vercel.app/',
    role: 'Développeur frontend',
    results: 'Conçu et construit une boutique soignée d accessoires masculins.',
    image: '/images/projects/refined-man.png',
  },
];
